services:
  notificationservice:
    build: .
    ports:
      - "8083:8083"
    environment:
      CustomerService__BaseUrl: "http://customerservice:8084"
      Payment__BaseUrl: "http://localhost:8081"
