services:
  storeservice:
    build: .
    ports:
      - "8083:8083"
    environment:
      ConnectionStrings__DefaultConnection: "Host=host.docker.internal;Port=5432;Database=egeeks_store;Username=postgres;Password=root"
